config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :employees
  resources :commodities
  resources :commodity_inventories
  resources :trading_records
  resources :wages
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commodity.rb
class Commodity < ApplicationRecord
end

app/models/commodity_inventory.rb
class CommodityInventory < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/trading_record.rb
class TradingRecord < ApplicationRecord
end

app/models/update_event.rb
class UpdateEvent < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify :before_add => :before_add_method #增加角色时，要做些什么
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  validates :name, presence: { message: "请填写姓名"}
  validates :name, uniqueness: { message: "已有其他用户使用该用户名"}

end

app/models/wage.rb
class Wage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  added_attrs = [:name, :email, :password, :password_confirmation]
  devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  layout 'home'
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	 
  layout 'home'
  def index
    
	end
end

app/controllers/trading_records_controller.rb
class TradingRecordsController < ApplicationController
  layout 'home'

  def index
    @trading_records = TradingRecord.all
  end

  def new
    @trading_record = TradingRecord.new
    @commodities = Commodity.all
    @employees = Employee.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'home'
  before_action :required_is_admin

  def index
    @users = User.where.not(id: current_user.id).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "新增#{@user.name} 成功"
      redirect_to users_path
    else
      flash[:warning] = "新增失败"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(new_params)
      flash[:notice] = "#{@user.name} 的信息更新成功"
      redirect_to user_path(params[:id])
    else
      flash[:warngin] = "更新信息失败"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "#{@user.name} 已删除"
    redirect_to users_path
  end

  private

    def user_params
      params.require(:users).permit(:name, :password, :password_confirmation)
    end

end

app/controllers/wages_controller.rb
class WagesController < ApplicationController
  layout 'home'
  def index
    @employees = Employee.all
  end

  def show
    @wage = Wage.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning" 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trading_records_helper.rb
module TradingRecordsHelper
end

app/helpers/wages_helper.rb
module WagesHelper
end

app/views/trading_records/index.html.erb
<div id="preloader">
  <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>
<div class="contentpanel">
  <div class="panel panel-body">
    <header style="text-align: center">
      <h4>过往交易记录列表</h4>
    </header>

    <div class="content-body"> 
      <div class="panel">
        <div class="panel-heading" style="background-color: #fff;">
          <span style="display:inline-block;">
            <%= form_tag "#", method: :get do%>
              <%= label_tag :"请选择年份和月份：" %>
              <%= select_tag(:year, options_for_select(Wage.pluck(:year).uniq), {:required => "true"}) %>
              <%= select_tag(:month, options_for_select(Wage.pluck(:month).uniq), {:required => "true"}) %>
              <%= submit_tag :筛选 %>
              <% end %>
          </span>
          <span style="float: right;"> 
          </span>
        </div>
      </div>
      <div class="content-table" style="clear:both;">
        <table>
          <thead>
            <tr>
              <th>商品名称</th>
              <th>商品编码</th>
              <th>员工名称</th>
              <th>员工工号</th>
              <th>交易数量</th>
              <th>原销售价</th>
              <th>折扣</th>
              <th>折后价</th>
              <th>总交易额</th>
              <th>经办人</th>
              <th>交易时间</th>
              <th>操作</th> 
            </tr>
          </thead>
          <tbody>
            <% @trading_records.each do |trading_record| %>
              <% commodity = Commodity.find(trading_record.commodity_id) %>
              <% employee = Employee.find(trading_record.employee_id) %>
              <tr>
                <td><%= commodity.name %></td>
                <td><%= commodity.commodity_code %></td>
                <td><%= employee.name %></td>
                <td><%= employee.job_number %></td>
                <td><%= trading_record.quantity %><%= commodity.unit %></td>
                <td><%= commodity.selling_price %>元</td>
                <td><%= (trading_record.discount * 100).to_i %>%</td>
                <td><%= (commodity.selling_price) * (trading_record.discount) %>元</td>
                <td><%= trading_record.total_amount %></td>
                <td><%= trading_record.operator %></td>
                <td><%= trading_record.created_at.to_datetime.strftime("%Y年%m月%d日%H时%M分") %></td>
                <td><%= link_to("修改", "#",class:"btn btn-primary btn-xs") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>      
      </div>
    </div>
  </div>
 </div>

app/views/trading_records/new.html.erb
<div id="preloader">
  <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>
<div class="contentpanel">
  <div class="panel panel-body">
    <header style="text-align: center">
      <h4>录入交易记录</h4>
    </header>

  <div class="content-body"> 
    <div class="panel">
      <div class="panel-heading" style="background-color: #fff;">
        <span style="display:inline-block;">
          <%= form_tag "#", method: :get do%>
            <%= label_tag :"请选择商品类型：" %>
            <%= select_tag(:commodity_type, options_for_select(Commodity.pluck(:commodity_type_name).uniq), {:required => "true"}) %>
            <%= submit_tag :筛选 %>
          <% end %>
        </span>
        <span style="float: right;"> 
          <%= link_to("查看过往交易记录", trading_records_path,class:"btn btn-primary-upload pull-right") %>
        </span>
      </div>
      <div class="content-table" style="clear:both;">
        <%= form_tag trading_records_path, method: :post do %>
          <table>
            <thead>
              <tr>
                <th>商品编码</th>
                <th>商品名称</th>
                <th>计量单位</th>
                <th>规格型号</th>
                <th>销售价</th>
                <th>销售数量</th>
                <th>员工姓名</th>
                <th>折扣</th>
              </tr>
            </thead>
            <tbody>
              <% @commodities.each do |commodity| %>
                <tr>
                  <td><%= commodity.commodity_code %></td>
                  <td><%= commodity.name %></td>
                  <td><%= commodity.unit %></td>
                  <td><%= commodity.standart %></td>
                  <td><%= commodity.selling_price %></td>
                  <td><%= text_field_tag :trading_quantity %><%= commodity.unit %></td>
                  <td><%= select_tag(:employee_name, options_for_select(@employees.collect{ |u| u.name }), {:prompt => "请选择", :required => "true"})  %></td>
                  <td><%= text_field_tag :discount %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br><br><br>
          <%= submit_tag :确定录入, class: "btn btn-primary-upload pull-right" %>
        <% end %>      
      </div>
    </div>
  </div>
 </div>