config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :employees
  resources :commodities
  resources :commodity_inventories
  resources :trading_records
  resources :wages
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commodity.rb
class Commodity < ApplicationRecord
end

app/models/commodity_inventory.rb
class CommodityInventory < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/trading_record.rb
class TradingRecord < ApplicationRecord
end

app/models/update_event.rb
class UpdateEvent < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify :before_add => :before_add_method #增加角色时，要做些什么
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  validates :name, presence: { message: "请填写姓名"}
  validates :name, uniqueness: { message: "已有其他用户使用该用户名"}

end

app/models/wage.rb
class Wage < ApplicationRecord
end

app/controllers/commodity_inventories_controller.rb
class CommodityInventoriesController < ApplicationController
  layout 'home'
  def index
    @commodities = Commodity.all
  end

  def show
    @commodity = Commodity.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  layout 'home'
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	 
  layout 'home'
  def index
    
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'home'
  before_action :required_is_admin

  def index
    @users = User.where.not(id: current_user.id).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "新增#{@user.name} 成功"
      redirect_to users_path
    else
      flash[:warning] = "新增失败"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(new_params)
      flash[:notice] = "#{@user.name} 的信息更新成功"
      redirect_to user_path(params[:id])
    else
      flash[:warngin] = "更新信息失败"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "#{@user.name} 已删除"
    redirect_to users_path
  end

  private

    def user_params
      params.require(:users).permit(:name, :password, :password_confirmation)
    end

end

app/controllers/wages_controller.rb
class WagesController < ApplicationController
  layout 'home'
  def index
    @employees = Employee.all
  end

  def show
    @wage = Wage.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/helpers/commodity_inventories_helper.rb
module CommodityInventoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning" 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trading_records_helper.rb
module TradingRecordsHelper
end

app/helpers/wages_helper.rb
module WagesHelper
end

app/views/commodity_inventories/index.html.erb
<div id="preloader">
  <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>
<div class="contentpanel">
  <div class="panel panel-body">
    <header style="text-align: center">
      <h4>货品库存页面</h4>
    </header>

    <div class="content-body"> 
      <div class="content-table" style="clear:both;">
        <table>
          <thead>
            <tr>
              <th>商品编码</th>
              <th>商品名称</th>
              <th>计量单位</th>
              <th>规格型号</th>
              <th>当前库存</th>
              <th>操作</th>
              <th>出入库记录</th>
            </tr>
          </thead>
          <tbody>
            <% @commodities.each do |commodity| %>
              <% if CommodityInventory.where(commodity_id: commodity.id).present? %>
                <% commodity_inventories = CommodityInventory.where(commodity_id: commodity.id) %>
                <tr>
                  <td><%= commodity.commodity_code %></td>
                  <td><%= commodity.name %></td>
                  <td><%= commodity.unit %></td>
                  <td><%= commodity.standart %></td>
                  <td><%= commodity_inventories.order("created_at DESC").first.current_inventory  %></td>
                  <td><%= link_to("入库", "#",class:"btn btn-primary btn-xs") %></td>
                  <td><%= link_to("查看记录", commodity_inventory_path(commodity.id),class:"btn btn-primary btn-xs") %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>      
      </div>
    </div>
  </div>
 </div>

app/views/commodity_inventories/show.html.erb
<div id="preloader">
  <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>
<div class="contentpanel">
  <div class="panel panel-body">
    <header style="text-align: center">
      <h4>货品出入库记录</h4>
    </header>

    <div class="content-body">
      <span style="display:inline-block;">
        <%= link_to("查看入库记录", "#",class:"btn btn-primary-upload pull-right") %>
        <%= link_to("查看出库记录", "#",class:"btn btn-primary-upload pull-right") %>
      </span> 
      <div class="content-table" style="clear:both;">
        <table>
          <thead>
            <tr>
              <th>商品编码</th>
              <th>商品名称</th>
              <th>计量单位</th>
              <th>规格型号</th>
              <th>操作类型</th>
              <th>操作数量</th>
              <th>剩余库存</th>
              <th>经办人</th>
              <th>时间</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
              <% if CommodityInventory.where(commodity_id: @commodity.id).present? %>
                <% commodity_inventories = CommodityInventory.where(commodity_id: @commodity.id) %>
                <% commodity_inventories.each do |commodity_inventory| %>
                  <tr>
                    <td><%= @commodity.commodity_code %></td>
                    <td><%= @commodity.name %></td>
                    <td><%= @commodity.unit %></td>
                    <td><%= @commodity.standart %></td>
                    <% inventory_hash = {true => "入库", false => "出库"} %>
                    <td><%= inventory_hash[commodity_inventory.operate_type] %></td>
                    <td><%= commodity_inventory.quantity %><%= @commodity.unit %></td>
                    <td><%= commodity_inventory.current_inventory %></td>
                    <td><%= commodity_inventory.operator %></td>
                    <td><%= commodity_inventory.created_at.to_datetime.strftime("%Y年%m月%d日%H时%M分") %></td>
                    <td><%= link_to("修改", "#",class:"btn btn-primary btn-xs") %></td>
                  </tr>
                <% end %>
              <% end %>
          </tbody>
        </table>      
      </div>
    </div>
  </div>
 </div>